repos:
  - repo: local
    hooks:
      - id: nbstripout
        name: nbstripout (poetry)
        entry: poetry run nbstripout
        language: system
        types: [jupyter]
        args: [--keep-output, --extra-keys, "metadata.kernelspec metadata.language_info.version"]

      - id: ruff
        name: ruff (poetry)
        entry: poetry run ruff check --fix
        language: system
        types: [python]

      - id: isort
        name: isort (poetry)
        entry: poetry run isort
        language: system
        types: [python]

      - id: black
        name: black (poetry)
        entry: poetry run black
        language: system
        types: [python]
